### ISSUE TITLE
What's the purpose of number of retries ?

### ISSUE THREAD

**Issue by danielkcz** [Brightspace/superagent-d2l-promise-queue#12]
From my understanding of the code and my attempts the number of retries doesn't really do anything except calculating next timeout. It won't stop retrying request when this number is reached. Based on docs I really did understand it like it will stop after reaching that number of requests. Sadly it just runs indefinitely no matter what. I could probably send PR if you consider it bug or wanted feature :)

**Comment by danielkcz** [comment]
Um...bump ?

**Comment by mdedys** [comment]
Sorry for the slow response to this. It should be stopping the number of retries and not running indefinitely. I will take a look at this in the next few days since if this is the case then it is a bug.
